### PR TITLE
Feature/test tooltips

### PR DESCRIPTION
**Pull request by wipascal**

### CODE REVIEW

**Review by dward2nd — APPROVED** [review]
I think the widget preview should contain more usage examples of the tooltip, especially possible directions and alignments it can be.

**Review by saemideluxe — CHANGES_REQUESTED** [review]
Could add the mentioned change in this PR as well? Regarding the replacement of BUTTON with DIV.

**Review by saemideluxe — APPROVED** [review]
Cool, thanks!

**Comment by saemideluxe** [comment]
Ah, isort failing btw.

**Pull request merged**
